fault_type: noise
inject_type: time
action_states: [1]
fault_duration_min: 0.2
fault_duration_max: 2
fault_amplitude_min: 0.1
fault_amplitude_max: 1
start_time_min: 2
start_time_max: 21
joint_names:
  - panda_joint1
  - panda_joint2
  - panda_joint3
  - panda_joint4
  - panda_joint5
  - panda_joint6
  - panda_joint7
