#!/usr/bin/env python
import rospy
from std_msgs.msg import Int32

current_data = 0


def callback(data):
    global current_data
    current_data = data.data
   

def publisher():
    pub = rospy.Publisher('action_states', Int32, queue_size=30)
    rate = rospy.Rate(100)
    while not rospy.is_shutdown():
        if current_data is not None:
            pub.publish(current_data)
            
        rate.sleep()

def subscriber():
    rospy.init_node('action_publisher')
    sub = rospy.Subscriber('/pose_state', Int32, callback)

if __name__ == '__main__':
    try:
        subscriber()
        publisher()
        
        rospy.spin()
        

    except rospy.ROSInterruptException:
        pass



